### ISSUE TITLE
Mycroft Skill failed to load

### ISSUE THREAD

**Issue by Y0ngg4n** [MycroftAI/skill-homeassistant#85]
```
 30486 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: skill-homeassistant.mycroftai
 14:22:37.421 | INFO     | 30486 | mycroft.skills.settings:get_local_settings:83 | /home/pi/.config/mycroft/skills/skill-homeassistant.mycroftai/settings.json
 14:22:37.425 | INFO     | 30486 | mycroft.skills.settings:get_local_settings:83 | /home/pi/.config/mycroft/skills/skill-homeassistant.mycroftai/settings.json
 14:22:37.589 | INFO     | 30486 | HomeAssistantSkill | Removing all handlers...
 14:22:37.591 | WARNING  | 30486 | mycroft.skills.fallback_skill:remove_fallback:185 | Could not find matching fallback handler
 14:22:37.599 | ERROR    | 30486 | mycroft.skills.skill_loader:_create_skill_instance:313 | Skill initialization failed with AttributeError("'NoneType' object has no attribute 'group'")
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/skill_loader.py", line 307, in _create_skill_instance
    self.instance.initialize()
  File "/opt/mycroft/skills/skill-homeassistant.mycroftai/__init__.py", line 91, in initialize
    self._setup()
  File "/opt/mycroft/skills/skill-homeassistant.mycroftai/__init__.py", line 37, in _setup
    ip = check_url(self.settings.get('host'))
  File "/opt/mycroft/skills/skill-homeassistant.mycroftai/ha_client.py", line 34, in check_url
    return matches.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
 14:22:37.604 | ERROR    | 30486 | mycroft.skills.skill_loader:_communicate_load_status:351 | Skill skill-homeassistant.mycroftai failed to load

```

**Comment by Tony763** [comment]
Hi @Y0ngg4n, could you provide, what did you have in host address?

**Comment by Tony763** [comment]
Would you also test [PR#86](https://github.com/Tony763/skill-homeassistant/tree/patch-8)? It should fix it.

**Comment by Y0ngg4n** [comment]
@Tony763 i cant say. There is no home assistant option at skill settings page.

**Comment by Tony763** [comment]
Host address :slightly_smiling_face:  
![image](https://user-images.githubusercontent.com/5598750/138279425-d2cc5c2a-ab3c-495e-948e-19b36e120dcc.png)

Or you can't see a Home Assistant in Mycroft skills setting page?
![image](https://user-images.githubusercontent.com/5598750/138279981-a90b85d4-a84e-4996-bc53-0bf11e42959f.png)

**Comment by Y0ngg4n** [comment]
![image](https://user-images.githubusercontent.com/30302975/138279985-5c72719a-3782-4eff-ae2f-62e1e7912967.png)
No home assistant

**Comment by Tony763** [comment]
Ok, so it failed at skill initialization so there is probably nothing set.  Could You test the proposed Fix?

**Comment by Y0ngg4n** [comment]
jup now it works

**Comment by Tony763** [comment]
Silly mistake, thanks for feedback. :slightly_smiling_face:

**Comment by stratus-ss** [comment]
@Y0ngg4n @Tony763 is this issue still valid or can it be closed?
